# Generated by Django 5.0.3 on 2024-04-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Console Name')),
                ('price', models.FloatField()),
                ('pdetails', models.CharField(max_length=100, verbose_name='Product Details')),
                ('cat', models.IntegerField(choices=[(1, 'PlayStation'), (2, 'Xbox'), (3, 'Nintendo Switch')], verbose_name='Product Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Availability')),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
