# Generated by Django 5.0.3 on 2024-04-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shophubapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='consoles',
            new_name='console',
        ),
    ]
