# Generated by Django 5.0.3 on 2024-04-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophubapp', '0004_alter_console_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Game Title')),
                ('price', models.FloatField()),
                ('gdetails', models.CharField(max_length=200, verbose_name='Game Details')),
                ('pltfrm', models.IntegerField(choices=[(1, 'PS'), (2, 'Xbox'), (3, 'Switch'), (4, 'PC')], verbose_name='Platform')),
                ('is_active', models.BooleanField(default=True, verbose_name='Availability')),
                ('gimage', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.AlterField(
            model_name='console',
            name='pdetails',
            field=models.CharField(max_length=200, verbose_name='Product Details'),
        ),
    ]
