# Generated by Django 5.0.3 on 2024-04-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophubapp', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='pdetails',
            field=models.CharField(max_length=500, verbose_name='Product Details'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gdetails',
            field=models.CharField(max_length=500, verbose_name='Game Details'),
        ),
    ]
